name: Build TTF
on:    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: "15.0.2"

    steps:

    - name: Set up Dependencies
      run: |
        sudo apt install make graphicsmagick libcairo2-dev python3-nototools pngquant zopfli rsync fonttools

    - name: Clone Repositories
      run: |
        git clone https://src.fedoraproject.org/rpms/twitter-twemoji-fonts.git
        cd twitter-twemoji-fonts
        git checkout 78a8615f22996e173b6489b004210f6302cfa456
        cd ..
        git clone https://github.com/jdecked/twemoji.git
        cd twemoji
        git checkout v${{ env.VERSION }}
        cd ..
        git clone https://github.com/googlefonts/noto-emoji.git
        cd noto-emoji
        git checkout ac1703e9d7feebbf5443a986e08332b1e1c5afcf

    - name: Patch Noto Emoji
      run: |
        cd noto-emoji
        patch -p1 -i ../twitter-twemoji-fonts/noto-emoji-use-system-pngquant.patch
        patch -p1 -i ../twitter-twemoji-fonts/noto-emoji-build-all-flags.patch
        patch -p1 -i ../twitter-twemoji-fonts/noto-emoji-use-gm.patch

    - name: Prepare Noto Emoji
      run: |
        cd noto-emoji
        mv NotoColorEmoji.tmpl.ttx.tmpl Twemoji.tmpl.ttx.tmpl
        sed -i 's/Noto Color Emoji/Twemoji/; s/NotoColorEmoji/Twemoji/; s/Copyright .* Google Inc\./Twitter, Inc and other contributors./; s/ Version .*/ '$VERSION'/; s/.*is a trademark.*//; s/Google, Inc\./Twitter, Inc and other contributors/; s,http://www.google.com/get/noto/,https://github.com/jdecked/twemoji/,; s/.*is licensed under.*/      Creative Commons Attribution 4.0 International/; s,http://scripts.sil.org/OFL,http://creativecommons.org/licenses/by/4.0/,' Twemoji.tmpl.ttx.tmpl
        cd ../twemoji/assets/72x72/
        for png in *.png; do
          mv $png emoji_u${png//-/_}
        done

    - name: Build Noto Emoji
      run: |
        cd noto-emoji
        ln -s $(which add_vs_cmap) $(which add_vs_cmap).py
        make EMOJI=Twemoji EMOJI_SRC_DIR=../twemoji/assets/72x72 FLAGS= BODY_DIMENSIONS=76x72
        mv Twemoji.ttf Twemoji-${{ env.VERSION }}.ttf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Twemoji ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Twemoji-${{ env.VERSION }}.ttf
        asset_name: Twemoji-${{ env.VERSION }}.ttf
        asset_content_type: application/x-font-ttf
      